# Generated by Django 5.2.1 on 2026-08-17 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectroCounters',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=100, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)], verbose_name='Номер счетчика')),
                ('client_name', models.CharField(max_length=40, unique=True, verbose_name='Наименование клиента')),
                ('address', models.IntegerField(default=100, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)], verbose_name='Сетевой адрес регистра')),
                ('transformation_coefficient', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Коэф. трансформации')),
                ('energy_indic', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Значение эн. на счетчике')),
                ('energy', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Значение энергии')),
            ],
            options={
                'verbose_name': 'Электросчетчик',
                'verbose_name_plural': 'Электросчетчики',
                'db_table': 'electro_counters',
            },
        ),
    ]
